---
- name: Create Traefik configuration directory
  file:
    path: "{{ docker_data_path }}/traefik/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ""
    - "logs"
    - "dynamic"
    - "certs"

- name: Create empty acme.json file for Let's Encrypt
  file:
    path: "{{ docker_data_path }}/traefik/certs/acme.json"
    state: touch
    mode: '0600'

- name: Generate Traefik static configuration
  template:
    src: traefik.yml.j2
    dest: "{{ docker_data_path }}/traefik/traefik.yml"
    mode: '0644'

- name: Generate Traefik dynamic configuration
  template:
    src: dynamic.yml.j2
    dest: "{{ docker_data_path }}/traefik/dynamic/dynamic.yml"
    mode: '0644'

- name: Deploy Traefik container with HTTPS support
  community.docker.docker_container:
    name: traefik
    image: "traefik:{{ traefik_version }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ docker_data_path }}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "{{ docker_data_path }}/traefik/dynamic:/etc/traefik/dynamic:ro"
      - "{{ docker_data_path }}/traefik/logs:/logs:rw"
      - "{{ docker_data_path }}/traefik/certs:/certs:rw"
    env:
      CF_API_EMAIL: "{{ cloudflare_email }}"
      CF_API_KEY: "{{ cloudflare_api_token }}"
    networks:
      - name: proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.dashboard.rule: "Host(`traefik.{{ domain_name }}`)"
      traefik.http.routers.dashboard.entrypoints: "websecure"
      traefik.http.routers.dashboard.service: "api@internal"
      traefik.http.routers.dashboard.middlewares: "authelia@file"
      traefik.http.routers.dashboard.tls.certresolver: "letsencrypt"
    recreate: yes